### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by Neville-N** [mechmotum/single-legged-time-trial#1]
- [x] Sketch of leg to visualize dimensions
- [ ] Hide cells with eom
- [x] Highlight where changes can be made, bike features, person features
- [ ] Make variables free or determined.
- [x] Try viscous damping torque in ankle

**Comment by moorepants** [comment]
I think we are good on this one.
